---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-f250392d554ef080a4c2112a3b3a2d7b
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/warrenwb/gitops-config.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/warrenwb/podinfo-deploy.git
